services:
  httpmock:
    image: alexliesenfeld/httpmock
    ports:
      - "4000:4000"
    environment:
      # If set to 1, the mock server will be configured to accept external connections (binds to 0.0.0.0).
      # Otherwise, only connections from your local machine will be accepted.
      - HTTPMOCK_EXPOSE=1
      # make sure the port is in sync with the ones specified in load.yml
      - HTTPMOCK_PORT=4000
    volumes:
      - ./data/Portability.zip:/data/Portability.zip
    networks:
      - data_portability_network

  data_portability_api_mocker:
    build: .
    environment:
      # Not automatically set when running in the container
      # Set it to make sure the method of body_from_file does not fail
      - "CARGO_MANIFEST_DIR=."
    volumes:
      - ./configuration:/app/configuration
      - ./data:/app/data
    depends_on:
      - httpmock
    networks:
      - data_portability_network

networks:
  data_portability_network:
